# Rollback hooks: POSITIONAL format + name suffix DISABLED
# Showcases: helm.sh/hook-weights positional + helm.sh/hook-name-suffix: "false"
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-rollback-hook
  labels:
    app: {{ .Release.Name }}
    hook-type: rollback
  annotations:
    helm.sh/hook: pre-rollback,post-rollback
    helm.sh/hook-weights: "-15,25"
    helm.sh/hook-name-suffix: "false"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        hook-type: rollback
    spec:
      containers:
        - name: rollback-hook
          image: {{ .Values.hookImage }}
          command:
            - /bin/sh
            - -c
            - |
              echo "============================================"
              echo "ROLLBACK HOOK RUNNING"
              echo "Hook Event: $HELM_HOOK_EVENT"
              echo "Hook Weight: $HELM_HOOK_WEIGHT"
              echo "Release: {{ .Release.Name }}"
              echo "============================================"
              sleep 3
      restartPolicy: Never
  backoffLimit: 0
